services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MID=${MID}
      - TID=${TID}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
