"""Add postback_delay to user_configs

Revision ID: 779bcb803de7
Revises: 74acd8d08219
Create Date: 2025-06-30 01:35:46.038375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779bcb803de7'
down_revision = '74acd8d08219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configs', sa.Column('postback_delay', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configs', 'postback_delay')
    # ### end Alembic commands ###
