"""Add postback_column_preferences to users table

Revision ID: d0a3657e8996
Revises: d95b03db7429
Create Date: 2025-06-22 11:51:55.630463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a3657e8996'
down_revision = 'd95b03db7429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postback_column_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('postback_column_preferences')
    # ### end Alembic commands ###
