"""Add display_order field to UserConfig

Revision ID: d95b03db7429
Revises: 
Create Date: 2025-06-19 12:24:40.794577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95b03db7429'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_configs', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
